Adding Python environments (main and dev) with README instructions
nsidc/JIRA-GitHub-ETL pull request #11
Opened 2023-06-06 22:50 UTC by IanSinColorado

Check out the instructions and see if the code segments work for reproducing the environment(s)

2023-06-07 00:53 UTC, MattF-NSIDC commented
Hey, @IanSinColorado ! Hope you don't mind my comments. The new repo appeared in my notifications and I decided to take a peek :)

In my experience the easiest way to deal with Conda environments is hand-maintaining an `environment.yml` which contains only your top-level dependencies (including both dev and runtime dependencies) and no sub-dependencies (i.e. include `beautifulsoup4`, but not `urllib3`).

`conda env export` is producing a record of your exact environment at that point in time, which may not be installable on other platforms and may even stop working next month on the same computer. If you instead hand-maintain an `environment.yml` which uses [compatible release](https://peps.python.org/pep-0440/#compatible-release) specification (e.g. `beautifulsoup4 ~=4.12`) and contains only things you directly `import`, then environment maintenance will be much easier over time. If you take this approach, I recommend avoiding `conda install <some-package>`, because that won't update your `environment.yml`. Instead, you could add `some-package` to your `environment.yml`, then do `conda env update` to apply the change to your environment.

An environment file with exact pins like you have is really useful if you want to build a docker image or run CI, but if you're not doing those things you may not need one at all. On NSIDC projects, we typically call those "lock files" following the nomenclature from NPM's `package-lock.json`, and often save them as `environment-lock.yml`. Some things to be aware of when using `conda env export`:

* the YAML outputs are platform-specific, and if you're using a Mac, that lock file may not work in GitHub Actions' Linux runners or on other developers' computers. For that, there's a tool called `conda-lock` which can create multi-platform lock files.
* the YAML outputs are specific to your personal computer; the last line of the YAML is `prefix: <some-path-on-your-computer>` and can (should?) be omitted. A one-liner: `conda env export | grep -v "^prefix:" > environment-lock.yml`
* the YAML outputs will contain your channel configuration from your `~/.condarc` file, which may not match the project's needs

[Here's](https://github.com/nsidc/sipn-reanalysis-plots/blob/main/environment.yml) an example of an `environment.yml` that's maintained with the above practices. The same repo also has an [`environment-lock.yml` file](https://github.com/nsidc/sipn-reanalysis-plots/blob/main/environment-lock.yml) which we produce using `conda env export` on a Linux machine so it can be built in GitHub Actions.

I'd also recommend against including your individual development dependencies (e.g. `vim`, `vscode`) in a project conda environment, and instead install them with Homebrew/Apt/whatever, as these may conflict with installed tools on other people's computers! Shared dev dependencies like `pytest` or `pre-commit` are more appropriate for `environment.yml`.

2023-06-07 20:29 UTC, IanSinColorado commented
I just added a commit with a manual environment.yml file. I tested it by starting to parse through the test JIRA issues XML file

2023-06-07 21:04 UTC, MattF-NSIDC commented
Looks great! Good call on writing up a quick test :sunglasses: I have a couple small suggestions:

* The `anaconda` channel is OK, but it's not worth using compared to the `conda-forge` channel. Packages on `anaconda` are built in private by ContinuumIO with little community input or control, while `conda-forge` packages are community maintained and built in the open from "feedstocks", which are GitHub repos containing packaging "recipes" only. I love this because when I need a new version that's not available, ContinuumIO won't take my call, but I can easily [open a feedstock PR](https://github.com/conda-forge/quarto-feedstock/pull/6) to get the version I need released. I suggest replacing `anaconda` with `conda-forge` and adding the channel `nodefaults` to the end of the list. This prevents conda from using the `anaconda` channel implicitly, which can be annoying. I'd even suggest creating or updating a `~/.condarc` that sets the channels for your user to always be `conda-forge` and `nodefaults`.
* [beautifulsoup4](https://anaconda.org/conda-forge/beautifulsoup4) and [lxml](https://anaconda.org/conda-forge/lxml) are both available on `conda-forge`, so those can be pulled out of the `pip` section; you don't need the `pip` section at all :)

2023-06-13 18:12 UTC, IanSinColorado commented
I have completed the issue of creating a reproducible conda environment. There are instructions in the README if you want to test it out. I think we need to merge this pull request and start a new branch/pull request, but in the meantime, I have started to load JIRA issue data from the jiraIssuesCryo.xml file. 
So far, I have functions to extract the title, JIRA issue link, and description (raw and pretty). I still need to extract the labels, status, and assignees from the XML file. Finally, I need to check if any other JIRA issue fields can be migrated to GitHub.

2023-06-21 14:31 UTC, jwfuller requested changes
Awesome start!

2023-06-21 14:31 UTC, jwfuller commented on README.md
> +2. Open the Anaconda Prompt (do a search on your computer for 'Anaconda Prompt' or open any terminal that can use the `conda` keyword; check using `conda --version` to see if a version pops up)
```suggestion
2. Verify to have [conda installed](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html): open a terminal and run `conda --version`. If a version number is returned, you have conda or miniconda installed.
```

2023-06-21 14:31 UTC, jwfuller commented on GitHubAPI.py
> +PAT = ''
You could set the PAT as an environmental variable or prompt for it and throw an error if it is not set.

2023-06-21 14:31 UTC, jwfuller commented on GitHubAPI.py
> +REPO_NAME = 'pythonapis'
Could you prompt for these values?

2023-06-21 14:31 UTC, jwfuller commented on README.md
>  ## Usage
Add the steps to run your scripts

2023-06-21 14:31 UTC, jwfuller commented on JIRAloading.py
> +with open('../testJIRA.xml', 'r') as f:
Prompt for file name

2023-06-21 14:31 UTC, jwfuller commented on JIRAloading.py
> +# print(issues[0])
Get rid of debugging statements

2023-06-21 14:31 UTC, jwfuller commented on JIRAloading.py
> +    # This function compiles the data from the titles, links, descriptions, labels, and checklists into a zipped array of tuples, where each tuple is all of the data for one issue.
Extend comment to include why is it important that they are tuples

2023-06-21 14:31 UTC, jwfuller commented on JIRAloading.py
> +    # print(issue[1])
Is this debugging code?

2023-06-21 14:31 UTC, jwfuller commented on GitHubAPI.py
> +        # 'accept': 'application/vnd.github+json'
Do you need this line in the future?

2023-06-21 14:31 UTC, jwfuller commented on GitHubAPI.py
> +# ****************************************************
Could you reuse the code form above?

2023-06-22 16:43 UTC, jwfuller approved these changes

2023-06-22 16:43 UTC, merged